before_script:
  - echo off
  - echo "Restoring NuGet Packages..."
  - '"src\nuget\NuGet.exe" restore "GitLabVS.sln"'
 
stages:
  - buildGitLabForVS
buildGitLabForVS:
  stage: buildGitLabForVS
  script:
  -  rebuildself.cmd    GitLabVS.sln
 
  artifacts:
    expire_in: 1 mos
    name: "%CI_PROJECT_NAME%_%CI_BUILD_ID%"
    paths:
    -  build/Release/GitLab.VisualStudio.vsix
    -  README.md
    
 